export default {
  games: [
    {
      gameId: "big5",
      gameKind: "machine",
      gameVariant: "lion",
      title: "Zama Fruits - Lion",
      url: "https://splitthepot.games/betika-ke/machine/lion?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/machine/lion?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/machine/lion/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_zama_fruits_lion_329c7baafc.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_zama_fruits_lion_329c7baafc.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_zama_fruits_lion_329c7baafc.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_zama_fruits_lion_329c7baafc.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_zama_fruits_wide_lion_2da3085a72.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_zama_fruits_wide_lion_2da3085a72.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_zama_fruits_wide_lion_2da3085a72.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_zama_fruits_wide_lion_2da3085a72.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "dice",
      gameKind: "to100",
      gameVariant: "spin",
      title: "Spin$",
      url: "https://splitthepot.games/betika-ke/to100/spin?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/to100/spin?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/to100/spin/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_spin_x3_729879d448_3295e040aa.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_spin_x3_729879d448_3295e040aa.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_spin_x3_729879d448_3295e040aa.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_spin_x3_729879d448_3295e040aa.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_spin_wide_x3_ff1f00a389_34a68047e9.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_spin_wide_x3_ff1f00a389_34a68047e9.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_spin_wide_x3_ff1f00a389_34a68047e9.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_spin_wide_x3_ff1f00a389_34a68047e9.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "hunt",
      gameKind: "hunter",
      gameVariant: "duck-pond",
      title: "Exploding Ducks",
      url: "https://splitthepot.games/betika-ke/hunter/duck-pond?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/hunter/duck-pond?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/hunter/duck-pond/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_ducks_copy_x3_f527159b2d.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_ducks_copy_x3_f527159b2d.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_ducks_copy_x3_f527159b2d.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_ducks_copy_x3_f527159b2d.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_ducks_wide_copy_2_x3_b0c7b4a7ba.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_ducks_wide_copy_2_x3_b0c7b4a7ba.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_ducks_wide_copy_2_x3_b0c7b4a7ba.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_ducks_wide_copy_2_x3_b0c7b4a7ba.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "wheel",
      gameKind: "multiplied",
      gameVariant: "fortune",
      title: "B! Fortune Spins",
      url: "https://splitthepot.games/betika-ke/multiplied/fortune?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/multiplied/fortune?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/multiplied/fortune/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_b_fortune_spins_wide_1519526d35_d9f17c9cb1.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_b_fortune_spins_wide_1519526d35_d9f17c9cb1.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_b_fortune_spins_wide_1519526d35_d9f17c9cb1.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_b_fortune_spins_wide_1519526d35_d9f17c9cb1.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_b_fortune_spins_square_88ca844be9_d5e38b38f1.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_b_fortune_spins_square_88ca844be9_d5e38b38f1.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_b_fortune_spins_square_88ca844be9_d5e38b38f1.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_b_fortune_spins_square_88ca844be9_d5e38b38f1.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "crash",
      gameKind: "crash",
      gameVariant: "taxicrash",
      title: "Bambuka",
      url: "https://splitthepot.games/betika-ke/crash/taxicrash?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/crash/taxicrash?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/crash/taxicrash/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_ke_taxicrash_3x_cbcbca8e1b_4d25b9173d.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_ke_taxicrash_3x_cbcbca8e1b_4d25b9173d.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_ke_taxicrash_3x_cbcbca8e1b_4d25b9173d.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_ke_taxicrash_3x_cbcbca8e1b_4d25b9173d.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 2250,
        height: 1266,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_ke_taxicrash_wide_3x_c2e0916a0c_42b61d1dfd.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_ke_taxicrash_wide_3x_c2e0916a0c_42b61d1dfd.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_ke_taxicrash_wide_3x_c2e0916a0c_42b61d1dfd.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_ke_taxicrash_wide_3x_c2e0916a0c_42b61d1dfd.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "mines",
      gameKind: "bomber",
      gameVariant: "goldrush",
      title: "Dhahabu Hub",
      url: "https://splitthepot.games/betika-ke/bomber/goldrush?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/bomber/goldrush?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/bomber/goldrush/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_gold_rush_x3_8e87719649_e7fa005882.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_gold_rush_x3_8e87719649_e7fa005882.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_gold_rush_x3_8e87719649_e7fa005882.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_gold_rush_x3_8e87719649_e7fa005882.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_gold_rush_wide_x3_3204de7d4d_ee00ccc3ad.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_gold_rush_wide_x3_3204de7d4d_ee00ccc3ad.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_gold_rush_wide_x3_3204de7d4d_ee00ccc3ad.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_gold_rush_wide_x3_3204de7d4d_ee00ccc3ad.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "boom",
      gameKind: "crashx",
      gameVariant: "superstar",
      title: "B!",
      url: "https://splitthepot.games/betika-ke/crashx/superstar?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/crashx/superstar?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/crashx/superstar/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 422,
        height: 422,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_crash_x3_6ce19343cc_d1b1bb821c.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_crash_x3_6ce19343cc_d1b1bb821c.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 0,
            height: 0,
            size: 0,
            path: null,
            url: "",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_crash_x3_6ce19343cc_d1b1bb821c.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 750,
        height: 422,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_crash_wide_x3_d3831a1dee_86fd753f01.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_crash_wide_x3_d3831a1dee_86fd753f01.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 0,
            height: 0,
            size: 0,
            path: null,
            url: "",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_crash_wide_x3_d3831a1dee_86fd753f01.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "plinko",
      gameKind: "balldrop",
      gameVariant: "plinko",
      title: "Plinko",
      url: "https://splitthepot.games/betika-ke/balldrop/plinko?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/balldrop/plinko?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/balldrop/plinko/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_plinko_x3_7b2264e673_c7d4715c1f.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_plinko_x3_7b2264e673_c7d4715c1f.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_plinko_x3_7b2264e673_c7d4715c1f.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_plinko_x3_7b2264e673_c7d4715c1f.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_plinko_wide_x3_092d111c31_24c6fec88c.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_plinko_wide_x3_092d111c31_24c6fec88c.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_plinko_wide_x3_092d111c31_24c6fec88c.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_plinko_wide_x3_092d111c31_24c6fec88c.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "magicnumbers",
      gameKind: "matchall",
      gameVariant: "dreams",
      title: "Dream$",
      url: "https://splitthepot.games/betika-ke/matchall/dreams?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/matchall/dreams?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/matchall/dreams/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_fafi_square_8f79cbe94d_1205ef3093.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_fafi_square_8f79cbe94d_1205ef3093.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_fafi_square_8f79cbe94d_1205ef3093.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_fafi_square_8f79cbe94d_1205ef3093.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_fafi_wide_51c9bb86d2_a22d296c15.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_fafi_wide_51c9bb86d2_a22d296c15.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_fafi_wide_51c9bb86d2_a22d296c15.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_fafi_wide_51c9bb86d2_a22d296c15.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "tower",
      gameKind: "tower",
      gameVariant: "jungle-gems",
      title: "Jungle Gems",
      url: "https://splitthepot.games/betika-ke/tower/jungle-gems?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/tower/jungle-gems?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/tower/jungle-gems/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_jungle_gems_x3_460340fbfc_4b24e0e09f.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_jungle_gems_x3_460340fbfc_4b24e0e09f.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_jungle_gems_x3_460340fbfc_4b24e0e09f.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_jungle_gems_x3_460340fbfc_4b24e0e09f.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_jungle_gems_wide_x3_a342df7933_868ab802df.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_jungle_gems_wide_x3_a342df7933_868ab802df.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_jungle_gems_wide_x3_a342df7933_868ab802df.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_jungle_gems_wide_x3_a342df7933_868ab802df.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "dice",
      gameKind: "to100",
      gameVariant: "paperplane",
      title: "Peperuka",
      url: "https://splitthepot.games/betika-ke/to100/paperplane?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/to100/paperplane?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/to100/paperplane/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_paperplane_x3_1d0ab6d439_39dc857120.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_paperplane_x3_1d0ab6d439_39dc857120.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_paperplane_x3_1d0ab6d439_39dc857120.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_paperplane_x3_1d0ab6d439_39dc857120.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_paperplane_wide_x3_77c115ed02_0f888008d0.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_paperplane_wide_x3_77c115ed02_0f888008d0.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_paperplane_wide_x3_77c115ed02_0f888008d0.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_paperplane_wide_x3_77c115ed02_0f888008d0.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "xfactor",
      gameKind: "xponential",
      gameVariant: "monkey-bizniz",
      title: "Monkey Bizniz",
      url: "https://splitthepot.games/betika-ke/xponential/monkey-bizniz?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/xponential/monkey-bizniz?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/xponential/monkey-bizniz/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_monkey_bizniz_x3_e2c9d18066_d218e71e7e.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_monkey_bizniz_x3_e2c9d18066_d218e71e7e.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_monkey_bizniz_x3_e2c9d18066_d218e71e7e.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_monkey_bizniz_x3_e2c9d18066_d218e71e7e.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_monkey_bizniz_wide_x3_f507ffa8f9_cd8d3cc68e.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_monkey_bizniz_wide_x3_f507ffa8f9_cd8d3cc68e.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_monkey_bizniz_wide_x3_f507ffa8f9_cd8d3cc68e.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_monkey_bizniz_wide_x3_f507ffa8f9_cd8d3cc68e.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "plinko",
      gameKind: "balldrop",
      gameVariant: "soccer-mania",
      title: "Soccer Mania",
      url: "https://splitthepot.games/betika-ke/balldrop/soccer-mania?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/balldrop/soccer-mania?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/balldrop/soccer-mania/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_soccer_mania_x3_d3dba60f76_98f4a6aaae.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_soccer_mania_x3_d3dba60f76_98f4a6aaae.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_soccer_mania_x3_d3dba60f76_98f4a6aaae.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_soccer_mania_x3_d3dba60f76_98f4a6aaae.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_soccer_mania_wide_x3_17d0beaa12_9082db0323.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_soccer_mania_wide_x3_17d0beaa12_9082db0323.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_soccer_mania_wide_x3_17d0beaa12_9082db0323.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_soccer_mania_wide_x3_17d0beaa12_9082db0323.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "magicnumbers",
      gameKind: "matchall",
      gameVariant: "tribalnumbers",
      title: "Magic Numbers",
      url: "https://splitthepot.games/betika-ke/matchall/tribalnumbers?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/matchall/tribalnumbers?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/matchall/tribalnumbers/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_magic_numbers_tribal_1c04303bb9_059b77a351.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_magic_numbers_tribal_1c04303bb9_059b77a351.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_magic_numbers_tribal_1c04303bb9_059b77a351.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_magic_numbers_tribal_1c04303bb9_059b77a351.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_magic_numbers_tribal_wide_4056325184_dc8ec447db.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_magic_numbers_tribal_wide_4056325184_dc8ec447db.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_magic_numbers_tribal_wide_4056325184_dc8ec447db.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_magic_numbers_tribal_wide_4056325184_dc8ec447db.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "multidice",
      gameKind: "multidice",
      gameVariant: "neondice",
      title: "Cheza Dice",
      url: "https://splitthepot.games/betika-ke/multidice/neondice?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/multidice/neondice?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/multidice/neondice/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_neondice_3x_35afb818d2_371fb62d95.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_neondice_3x_35afb818d2_371fb62d95.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_neondice_3x_35afb818d2_371fb62d95.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_neondice_3x_35afb818d2_371fb62d95.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_neondice_wide_3x_ecaffa1cee_cf3c2bc46d.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_neondice_wide_3x_ecaffa1cee_cf3c2bc46d.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_neondice_wide_3x_ecaffa1cee_cf3c2bc46d.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_neondice_wide_3x_ecaffa1cee_cf3c2bc46d.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "xfactor",
      gameKind: "xponential",
      gameVariant: "daredevil",
      title: "Panda Ngazi",
      url: "https://splitthepot.games/betika-ke/xponential/daredevil?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/xponential/daredevil?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/xponential/daredevil/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_daredevil_x3_590e921a67_bf3ac405b3.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_daredevil_x3_590e921a67_bf3ac405b3.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_daredevil_x3_590e921a67_bf3ac405b3.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_daredevil_x3_590e921a67_bf3ac405b3.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_daredevil_wide_x3_d6753f64d4_09911ef6e2.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_daredevil_wide_x3_d6753f64d4_09911ef6e2.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_daredevil_wide_x3_d6753f64d4_09911ef6e2.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_daredevil_wide_x3_d6753f64d4_09911ef6e2.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "golddigger",
      gameKind: "stages",
      gameVariant: "archeo",
      title: "Migodi",
      url: "https://splitthepot.games/betika-ke/stages/archeo?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/stages/archeo?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/stages/archeo/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_archeo_x3_8a047e62b5_5530fd1ef0.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_archeo_x3_8a047e62b5_5530fd1ef0.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_archeo_x3_8a047e62b5_5530fd1ef0.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_archeo_x3_8a047e62b5_5530fd1ef0.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_betika_archeo_wide_x3_fa232fae40_5aee576481.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_betika_archeo_wide_x3_fa232fae40_5aee576481.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_betika_archeo_wide_x3_fa232fae40_5aee576481.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_betika_archeo_wide_x3_fa232fae40_5aee576481.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
    {
      gameId: "rockpaperscissors",
      gameKind: "oneof3",
      gameVariant: "rps",
      title: "Rock Paper Scissors",
      url: "https://splitthepot.games/betika-ke/oneof3/rps?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/oneof3/rps?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/oneof3/rps/bet-history/{gameplayId}?token={token}",
      enabled: true,
      maintenance: false,
      squareX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 633,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 156,
            height: 156,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_rps_3x_516d8f9264_4a2e0fe331.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 211,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_rps_3x_516d8f9264_4a2e0fe331.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 422,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_rps_3x_516d8f9264_4a2e0fe331.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_rps_3x_516d8f9264_4a2e0fe331.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
      wideX3: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 1125,
        height: 633,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 245,
            height: 138,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/thumbnail_gameicon_rps_wide_3x_6794fcd546_980cde6281.png",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 375,
            height: 211,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x1_gameicon_rps_wide_3x_6794fcd546_980cde6281.png",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 750,
            height: 422,
            size: 0,
            path: null,
            url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/x2_gameicon_rps_wide_3x_6794fcd546_980cde6281.png",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/gameicon_rps_wide_3x_6794fcd546_980cde6281.png",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
  ],
  directGames: [
    {
      gameId: "crash",
      gameKind: "crashx",
      gameVariant: "comet",
      title: "Comet",
      url: "https://splitthepot.games/betika-ke/crashx/comet?token={token}",
      freeToPlayUrl:
        "https://splitthepot.games/betika-ke/crashx/comet?token=freetoplay",
      bethistoryUrl:
        "https://splitthepot.games/betika-ke/crashx/comet/bet-history/{gameplayId}?token={token}",
      enabled: false,
      maintenance: false,
      icon: {
        name: "",
        alternativeText: "",
        caption: "",
        width: 128,
        height: 128,
        formats: {
          thumbnail: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 0,
            height: 0,
            size: 0,
            path: null,
            url: "",
          },
          x1: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 0,
            height: 0,
            size: 0,
            path: null,
            url: "",
          },
          x2: {
            name: "",
            hash: "",
            ext: "",
            mime: "",
            width: 0,
            height: 0,
            size: 0,
            path: null,
            url: "",
          },
        },
        hash: "",
        ext: "",
        mime: "",
        size: 0,
        url: "https://ststrapiv4westeu.blob.core.windows.net/strapiv4-uploads/assets/comet_icon_4846fb5547_787b74fe8f.svg",
        previewUrl: "",
        provider: "",
        provider_metadata: "",
        updated_at: "0001-01-01T00:00:00Z",
      },
    },
  ],
  extremeGames: [],
  dataFreeGames: null,
  updated: "2025-11-27T10:44:21.378Z",
};
